### ISSUE TITLE
Slice test case fails

### ISSUE THREAD

**Issue by pjotrp** [biod/sambamba#391]
Compiling sambamba with -cov (for coverage) has this test fail 

        sambamba slice -L test/chr2_chr3_test_region.bed test/issue_204.bam

with

```
#19 0x00000000005cc2a7 in _D3std5array__T14arrayAllocImplVbi0TAhTmZQBaFNaNbmZQp (_param_0=524288)
    at /gnu/store/qzcgba5bflcgxsinabfpfy7j5nddvj4f-ldc-1.14.0/include/d/std/array.d:950
#20 0x000000000052adb5 in _D3std5array__T18uninitializedArrayTAhTmZQBaFNaNbNemZQr (_param_0=524288)
    at /gnu/store/qzcgba5bflcgxsinabfpfy7j5nddvj4f-ldc-1.14.0/include/d/std/array.d:819
#21 0x000000000056a8d6 in _D3bio4core4bgzf11inputstream15BgzfInputStream6__ctorMFCQCcQCbQBzQBx17BgzfBlockSupplierC3std11parallelism8TaskPoolCQEjQEi5utils7memoize__T5CacheTSQFoQFnQFl5block9BgzfBlockTSQGpQGoQGmQBb21DecompressedBgzfBlockZQCtmZCQIfQIeQIcQIaQHq (this=0x7ffff7b52b00, supplier=0x7ffff7b45dd0, 
    pool=0x7ffff7b47480, cache=0x0, buffer_size=0) at /export/export/local/wrk/izip/git/opensource/D/sambamba/BioD/bio/core/bgzf/inputstream.d:454
#22 0x0000000000574283 in _D3bio3std3hts3bam19randomaccessmanager19RandomAccessManager__T15readsFromChunksSQDbQDaQCzQCy9readrange11withOffsetsTASQEn4core4bgzf5chunk5ChunkZQDeMFQBhZSQFxQFwQFvQFuQCw__T12BamReadRangeSQHeQHdQHcQHbQEdQDwZQBi (this=0x7ffff7b47f00, chunks=...)
    at /export/export/local/wrk/izip/git/opensource/D/sambamba/BioD/bio/std/hts/bam/randomaccessmanager.d:344
#23 0x0000000000566593 in _D3bio3std3hts3bam19randomaccessmanager19RandomAccessManager__T8getReadsSQCtQCsQCrQCq9readrange11withOffsetsZQBuMFSQEjQEiQEhQEg6region9BamRegionZSQFoQFnQFmQFlQFkQEs__T13BamReadFilterTSQHaQGzQGyQGxQEh__T12BamReadRangeSQIhQIgQIfQIeQFoQFhZQBiZQCv (this=0x7ffff7b47f00, region=...)
    at /export/export/local/wrk/izip/git/opensource/D/sambamba/BioD/bio/std/hts/bam/randomaccessmanager.d:311
#24 0x00000000004a884c in _D3bio3std3hts3bam9reference17ReferenceSequence16endVirtualOffsetMFZSQCp4core4bgzf13virtualoffset13VirtualOffset (this=0x1)
    at /export/export/local/wrk/izip/git/opensource/D/sambamba/BioD/bio/std/hts/bam/reference.d:118
#25 0x00000000004a8252 in _D8sambamba5slice12fetchRegionsFC3bio3std3hts3bam6reader9BamReaderASQBj4core6region6RegionKC7contrib6undead6stream6StreamZv (bam=0x7ffff7b49100, regions=..., stream=@0x7fffffffe0c8: 0x7ffff7b47980) at /export/export/local/wrk/izip/git/opensource/D/sambamba/sambamba/slice.d:158
#26 0x00000000004ab67e in sambamba.slice.slice_main(immutable(char)[][]) (args=...) at /export/export/local/wrk/izip/git/opensource/D/sambamba/sambamba/slice.d:348
#27 0x00000000004daa44 in D main (args=...) at /export/export/local/wrk/izip/git/opensource/D/sambamba/sambamba/main.d:111
```

**Comment by pjotrp** [comment]
Seems to work now.
